SiteYonetim/SiteYonetim/Models/ErrorViewModel.cs
using System;

namespace SiteYonetim.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SiteYonetim/SiteYonetim/Models/UserDaire.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteYonetim.Models
{
    public class UserDaire
    {
        public int ID { get; set; }
        public string BlokAdi{ get; set; }
    }
}

SiteYonetim/SiteYonetim/Controllers/DaireController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteYonetim.Controllers
{
    public class DaireController : Controller
    {
        DaireManager cm = new DaireManager(new EfDaireRepository());
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public PartialViewResult PartialAddDaire()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult PartialAddDaire(Daire p)
        {
            //p.DaireNUMARA = ToString();
            cm.DaireAdd(p);
            //Response.Redirect("/Site/SiteReadAll/" + 1);
            return PartialView();
        }

        public PartialViewResult DaireListBySite(int id)
        {
            var values=cm.GetList(id);
            return PartialView(values);
        }
    }
}

SiteYonetim/SiteYonetim/Controllers/ErrorPageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteYonetim.Controllers
{
    public class ErrorPageController : Controller
    {
        public IActionResult Error1(int code)
        {
            return View();
        }
    }
}

SiteYonetim/SiteYonetim/Controllers/EvController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteYonetim.Controllers
{
    public class EvController : Controller
    {
        EvManager em = new EvManager(new EfEvRepository());
        [HttpGet]
        public PartialViewResult SubscribeMail()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult SubscribeMail(Ev p)
        {
           
            em.AddEv(p);
            Response.Redirect("/Site/SiteReadAll/" + 1);
            return PartialView();
        }
    }
}

SiteYonetim/SiteYonetim/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiteYonetim.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SiteYonetim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Test()
        {
            return View();
        }
    }
}

SiteYonetim/SiteYonetim/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteYonetim.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SiteYonetim/SiteYonetim/Controllers/RegisterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteYonetim.Controllers
{
    public class RegisterController : Controller
    {
        BilgiManager bm = new BilgiManager(new EfBilgiRepository());


        [HttpGet]
        public IActionResult Index()
        {

            return View();
        }





        [HttpPost]
        public IActionResult Index(Bilgi p)
        {
            BilgiValidator bv = new BilgiValidator();
            ValidationResult results = bv.Validate(p);
            if (results.IsValid)
            {
                p.EvSahibiName = "Ev sahibi";
                p.EvSahibiMail = "evsahibi@gmail.com";
                bm.BilgiAdd(p);

                return RedirectToAction("Index", "Site");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
           
        }
    }
}

SiteYonetim/SiteYonetim/Controllers/SiteController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteYonetim.Controllers
{
    public class SiteController : Controller
    {
        SiteManager sm = new SiteManager(new EfSiteRepository());
        public IActionResult Index()
        {
            var values = sm.GetSiteWithCategory();
            return View(values);
        }
        public IActionResult SiteReadAll(int id)
        {
            ViewBag.i = id;
            var values = sm.GetSiteByID(id);
            return View(values);

        }
    }
}

SiteYonetim/SiteYonetim/Views/Category/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    Layout = null;
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>KATEGORİ ADI</th>
        <th>DURUMU</th>
        <th>DETAYLAR</th>
        <th>SİL</th>




    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryID</td>
            <td>@item.CategoryName</td>
            <td>@item.CategoryStatus</td>
            <td><a href="#" class="btn btn-warning">DETAYLAR</a></td>
            <td><a href="#" class="btn btn-danger">SİL</a></td>

        </tr>
    }
</table>

SiteYonetim/SiteYonetim/Views/Daire/DaireListBySite.cshtml
@model IEnumerable<EntityLayer.Concrete.Daire> 
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            border: 1px solid #ddd;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }
    </style>
</head>
<body>

    <h2>Menekşe Sitesi Daireleri</h2>
    <p></p>
    <p></p>

    <div style="overflow-x:auto;">
        <table>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Points</th>
                <th>Points</th>
                <th>Points</th>
                <th>Points</th>
                <th>Points</th>
                <th>Points</th>
                <th>Points</th>
                <th>Points</th>
                <th>Points</th>
                <th>Points</th>
            </tr>
            <tr>
                <td>Jill</td>
                <td>Smith</td>
                <td>50</td>
                <td>50</td>
                <td>50</td>
                <td>50</td>
                <td>50</td>
                <td>50</td>
                <td>50</td>
                <td>50</td>
                <td>50</td>
                <td>50</td>
            </tr>
            <tr>
                <td>Eve</td>
                <td>Jackson</td>
                <td>94</td>
                <td>94</td>
                <td>94</td>
                <td>94</td>
                <td>94</td>
                <td>94</td>
                <td>94</td>
                <td>94</td>
                <td>94</td>
                <td>94</td>
            </tr>
            <tr>
                <td>Adam</td>
                <td>Johnson</td>
                <td>67</td>
                <td>67</td>
                <td>67</td>
                <td>67</td>
                <td>67</td>
                <td>67</td>
                <td>67</td>
                <td>67</td>
                <td>67</td>
                <td>67</td>
            </tr>
        </table>
    </div>

</body>
</html>

SiteYonetim/SiteYonetim/Views/Daire/PartialAddDaire.cshtml
<h1></h1> <div class="comment-top">
    <h4>Daire Kayıt İşlemi</h4>
    <div class="comment-bottom">
        <form action="/Daire/PartialAddDaire/" method="post">
            <input class="form-control" type="text" name="BlokNUMARA" placeholder="Blok Bilgisi" required="">
            <input class="form-control" type="text" name="DaireNUMARA" placeholder="Daire Numarası" required="">

            <input class="form-control" type="text" name="DaireKAT" placeholder="Daire KAT" required="">

            <textarea class="form-control" name="DaireACIKLAMA" placeholder="Daire Açıklama" required=""></textarea>
            <button type="submit" class="btn btn-primary submit">Kaydet</button>
        </form>
    </div>
</div>

SiteYonetim/SiteYonetim/Views/ErrorPage/Error1.cshtml
@{
    Layout = null;
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Bicycle Error Page Responsive Widget Template :: W3layouts</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords"
          content="Bicycle Error Page Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
    </script>
    <!-- //Meta tag Keywords -->
    <!--/Style-CSS -->
    <link rel="stylesheet" href="~/weberror/css/style.css" type="text/css" media="all" />
    <!--//Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="~/weberror/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
</head>

<body>
    <section class="w3l-error-61-404">
        <!-- /error-61-section -->
        <div class="error-61-mian">
            <div class="wrapper">
                <div class="errors-16-top">
                    <div class="errors-16-info">
                        <h3>404 </h3>

                        <p>Oops! Sayfa Bulunamadı</p>
                        <form action="#" method="post" class="d-flex error-page-form">
                            <input type="search" placeholder="Aradığınız Kelime" required="required">
                            <button type="submit"><span class="fa fa-search" aria-hidden="true"></span></button>
                        </form>
                        <div class="social-coming-icons">
                            <a href="#" title="Facebook" class="footer-fb">
                                <span class="fa fa-facebook"
                                      aria-hidden="true"></span>
                            </a>
                            <a href="#" title="Twitter" class="footer-tw">
                                <span class="fa fa-twitter"
                                      aria-hidden="true"></span>
                            </a>
                            <a href="#" title="Google Plus" class="footer-gg">
                                <span class="fa fa-google-plus"
                                      aria-hidden="true"></span>
                            </a>
                            <a href="#" title="Linkedin" class="footer-lin">
                                <span class="fa fa-linkedin"
                                      aria-hidden="true"></span>
                            </a>
                        </div>

                    </div>

                </div>
                <div class="copyright-footer">
                    <div class="copy-right">
                        <p>
                            © @DateTime.Now.Year Site Yönetim Projesi Tüm Hakları Saklıdır | Design by
                            <a href="http://w3layouts.com/" target="_blank">W3layouts</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- //error-61-section -->
</body>

</html>

SiteYonetim/SiteYonetim/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Oturum Aç</h3>
        <div class="row inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                <form action="#" method="post">
                    <div class="form-group">
                        <label for="exampleInputEmail1 mb-2">Mail Adresi</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" required="">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1 mb-2">Şifre</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="" required="">
                    </div>
                    <div class="form-check mb-2">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Beni Hatırla</label>
                    </div>
                    <button type="submit" class="btn btn-primary submit mb-4">Giriş Yap
                    </button>
                    <p><a href="register.html">Bir hesabın yok mu?</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

SiteYonetim/SiteYonetim/Views/Register/Index.cshtml
@model EntityLayer.Concrete.Bilgi

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>


<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Yönetici Kayıt Sayfası</h3>
        <div class="inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                @using (Html.BeginForm("Index", "Register", FormMethod.Post))
                {
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom01">Adınız Soyadınız</label>
                            @Html.TextBoxFor(x=>x.YoneticiName,new { @class = "form-control" })
                            @Html.ValidationMessageFor(x=>x.YoneticiName,"",new { @class = "text-danger" })
                            @*<input type="text" class="form-control" id="validationDefault01" name="YoneticiName" placeholder="" required="">*@
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom02">Mail Adresi</label>
                            @Html.TextBoxFor(x => x.YoneticiMail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.YoneticiMail, "",new { @class = "text-danger" })
                            @*<input type="text" class="form-control" id="validationDefault02" name="YoneticiMail" placeholder="" required="">*@
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword1 mb-2">Şifre</label>
                            @Html.TextBoxFor(x => x.YoneticiPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.YoneticiPassword,"", new { @class = "text-danger" })
                            @*<input type="password" class="form-control" id="password1" name="YoneticiPassword" placeholder="" required="">*@
                        </div>

                        <hr />
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label"> İl Seç:</label>


                                    <select name="products" class="form-control" asp-items="@ViewBag.cities"></select>


                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info">Kayıt OL</button>
                    <p>
                        <a href="#" id="btn1">Tüm Şartları Okudum Kabul Ediyorum.</a>
                    </p>

                }

            </div>
        </div>
    </div>
    <br />
    
    <script>
        $('#btn1').click(function () {
            swal("Site Kabul Şartları","Sitemizde verdiğiniz mail adresi üzerinden bilgi ve haber e-postaları gönderilmeye "+
                " devam edilecektir. Eğer e-posta bülteninden çıkmak isterseniz mail ileti dizisini "+
                "durdurabilirsiniz şifre ve mail adresleriniz şifrelenmiş formatta herhangi bir " +
                "kullanıcının görmeyeceği şekilde veri tabanlarımızda saklanmaktadır.");
        });
    </script>
</section>

SiteYonetim/SiteYonetim/Views/Shared/Components/CategoryList/Default.cshtml
@model IEnumerable<EntityLayer.Concrete.Category>
<div class="tech-btm">
    <h4>Kategoriler</h4>
    <ul class="list-group single">
        @foreach (var item in Model)
        {
            <li class="list-group-item d-flex justify-content-between align-items-center">
            @item.CategoryName
                <span class="badge badge-primary badge-pill">14</span>
            </li>
        }
        
    </ul>
</div>

SiteYonetim/SiteYonetim/Views/Shared/Components/DaireList/Default.cshtml
@model IEnumerable<SiteYonetim.Models.UserDaire>

@foreach (var item in Model)
{

    <p>@item.ID</p>
    <p>@item.BlokAdi</p>

}

SiteYonetim/SiteYonetim/Views/Shared/Components/DaireListBySite/Default.cshtml
@model IEnumerable<EntityLayer.Concrete.Daire>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            border: 1px solid #ddd;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }
    </style>
</head>
<body>



    <div style="overflow-x:auto;">
        @if ((int)Model.Count() > 0)
        {
            <h2>Menekşe Sitesi Daireleri</h2>

        }
            else
            {
                <h2>Henüz herhangi bir daire yok.
                <br />Daire bilgilerini yazabilirsiniz.</h2>

            }
        <table>

            <tr>
                <th>Daire ID</th>
                <th>Blok Numarası</th>
                <th>Daire Numarası</th>
                <th>Daire Katı</th>
                <th>Daire Alanı</th>
                <th>Daire Açıklaması</th>

            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.DaireID</td>
                    <td>@item.BlokNUMARA</td>

                    <td>@item.DaireNUMARA</td>

                    <td>@item.DaireKAT</td>

                    <td>@item.DaireALAN</td>
                    <td>@item.DaireACIKLAMA</td>


                </tr>
            }

        </table>
    </div>

</body>
</html>

SiteYonetim/SiteYonetim/Views/Shared/Partial2.cshtml
<div class="header_top" id="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="index.html">
                        ANASAYFA
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="about.html">SİTE BİLGİLERİ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">DAİRE BİLGİLERİ </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">İLETİŞİM</a>
                </li>

            </ul>
            <form action="#" method="post" class="form-inline my-2 my-lg-0 header-search">
                <input class="form-control mr-sm-2" type="search" placeholder="Aranacak Kelime" name="Search" required="">
                <button class="btn btn1 my-2 my-sm-0" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>



        </div>
    </nav>

</div>

SiteYonetim/SiteYonetim/Views/Shared/Partial3.cshtml
<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
    <span>Hoşgeldiniz </span>
    <span class="mx-lg-4 mx-md-2  mx-1">
        <a href="login.html">
            <i class="fas fa-lock"></i> Giriş Yap
        </a>
    </span>
    <span>
        <a href="/Register/Index">
            <i class="far fa-user"></i> Kayıt OL
        </a>
    </span>
</div>

SiteYonetim/SiteYonetim/Views/Shared/Partial4.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">
                <h3>Hakkımızda</h3>
                <p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. lacinia eget consectetur sed, convallis at tellus..</p>
                <div class="read">
                    <a href="single.html" class="btn btn-primary read-m">Devamını Oku</a>
                </div>
            </div>
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">

                <div class="tech-btm">
                    <h3>Son Postlar</h3>
                    <div class="blog-grids row mb-3">
                        <div class="col-md-5 blog-grid-left">
                            <a href="single.html">
                                <img src="~/CoreBlogTema/images/4.jpg" class="card-img-top img-fluid" alt="">
                            </a>
                        </div>
                        <div class="col-md-7 blog-grid-right">

                            <h5>
                                <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                            </h5>
                            <div class="sub-meta">
                                <span>
                                    <i class="far fa-clock"></i> 20 Jan, 2018
                                </span>
                            </div>
                        </div>

                    </div>
                    <div class="blog-grids row mb-3">
                        <div class="col-md-5 blog-grid-left">
                            <a href="single.html">
                                <img src="~/CoreBlogTema/images/5.jpg" class="card-img-top img-fluid" alt="">
                            </a>
                        </div>
                        <div class="col-md-7 blog-grid-right">

                            <h5>
                                <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                            </h5>
                            <div class="sub-meta">
                                <span>
                                    <i class="far fa-clock"></i> 20 Jan, 2018
                                </span>
                            </div>
                        </div>

                    </div>
                    <div class="blog-grids row mb-3">
                        <div class="col-md-5 blog-grid-left">
                            <a href="single.html">
                                <img src="~/CoreBlogTema/images/6.jpg" class="card-img-top img-fluid" alt="">
                            </a>
                        </div>
                        <div class="col-md-7 blog-grid-right">

                            <h5>
                                <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                            </h5>
                            <div class="sub-meta">
                                <span>
                                    <i class="far fa-clock"></i> 20 Jan, 2018
                                </span>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- subscribe -->
            <div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left">
                <h2>Signup to our newsletter</h2>
                <div class="subscribe-main text-left">
                    <div class="subscribe-form">
                        <form action="#" method="post" class="subscribe_form">
                            <input class="form-control" type="email" placeholder="Enter your email..." required="">
                            <button type="submit" class="btn btn-primary submit">Submit</button>
                        </form>
                        <div class="clearfix"> </div>
                    </div>
                    <p>We respect your privacy.No spam ever!</p>
                </div>
                <!-- //subscribe -->
            </div>
        </div>
        <!-- footer -->
        <div class="footer-cpy text-center">
            <div class="footer-social">
                <div class="copyrighttop">
                    <ul>
                        <li class="mx-3">
                            <a class="facebook" href="#">
                                <i class="fab fa-facebook-f"></i>
                                <span>Facebook</span>
                            </a>
                        </li>
                        <li>
                            <a class="facebook" href="#">
                                <i class="fab fa-twitter"></i>
                                <span>Twitter</span>
                            </a>
                        </li>
                        <li class="mx-3">
                            <a class="facebook" href="#">
                                <i class="fab fa-google-plus-g"></i>
                                <span>Google+</span>
                            </a>
                        </li>
                        <li>
                            <a class="facebook" href="#">
                                <i class="fab fa-pinterest-p"></i>
                                <span>Pinterest</span>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
            <div class="w3layouts-agile-copyrightbottom">
                <p>
                    © @DateTime.Now.Year  Weblog. All Rights Reserved | Design by
                    <a href="http://w3layouts.com/">W3layouts</a>
                </p>

            </div>
        </div>

        <!-- //footer -->


    </div>
</footer>

SiteYonetim/SiteYonetim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiteYonetim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SiteYonetim</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SiteYonetim - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>